service: handle-image
# app and org for use with dashboard.serverless.com
app: lambda-services
org: dolong
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  environment: 
    ALL_SIZE: 56x56,128x128,168x168,264x264,300x300,411x411,616x616,590x400,750x360,750x372,1242x616,1242x596,372x750,500x750,616x1242,828x1242
    BUCKET: coxude-images
package:
  include: ../../node_modules/**
functions:
  resize-image:
    handler: resize-handler.resizeImage 
    events:
      - s3:
          bucket: coxude-images
          event: s3:ObjectCreated:*
          rules:
            - prefix: default/
          existing: true